local path = ...

require(path .. '.datastructures.table')
require(path .. '.external')
require(path .. '.object')
require(path .. '.input')
require(path .. '.graphics.graphics')
require(path .. '.game.gameobject')
require(path .. '.game.ticks')
require(path .. '.game.group')
require(path .. '.game.physics')
require(path .. '.game.trigger')
require(path .. '.game.machine')
require(path .. '.math.math')
require(path .. '.math.vector')
require(path .. '.math.spring')
require(path .. '.math.polygon')
require(path .. '.math.chain')
require(path .. '.math.line')
require(path .. '.math.rectangle')
